/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppWhatsappRouteImport } from './routes/_app.whatsapp'
import { Route as AppWellnessProgramsRouteImport } from './routes/_app.wellness-programs'
import { Route as AppTemplatesRouteImport } from './routes/_app.templates'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppEmployeesRouteImport } from './routes/_app.employees'
import { Route as AppDevicesRouteImport } from './routes/_app.devices'
import { Route as AppAuditLogsRouteImport } from './routes/_app.audit-logs'
import { Route as AppNotificationsIndexRouteImport } from './routes/_app.notifications.index'
import { Route as AppWellnessProgramsNewRouteImport } from './routes/_app.wellness-programs.new'
import { Route as AppWellnessProgramsIdRouteImport } from './routes/_app.wellness-programs.$id'
import { Route as AppNotificationsNewRouteImport } from './routes/_app.notifications.new'
import { Route as AppNotificationsIdRouteImport } from './routes/_app.notifications.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWhatsappRoute = AppWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const AppWellnessProgramsRoute = AppWellnessProgramsRouteImport.update({
  id: '/wellness-programs',
  path: '/wellness-programs',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesRoute = AppDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditLogsRoute = AppAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsIndexRoute = AppNotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => AppRoute,
} as any)
const AppWellnessProgramsNewRoute = AppWellnessProgramsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppWellnessProgramsRoute,
} as any)
const AppWellnessProgramsIdRoute = AppWellnessProgramsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppWellnessProgramsRoute,
} as any)
const AppNotificationsNewRoute = AppNotificationsNewRouteImport.update({
  id: '/notifications/new',
  path: '/notifications/new',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsIdRoute = AppNotificationsIdRouteImport.update({
  id: '/notifications/$id',
  path: '/notifications/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/devices': typeof AppDevicesRoute
  '/employees': typeof AppEmployeesRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/templates': typeof AppTemplatesRoute
  '/wellness-programs': typeof AppWellnessProgramsRouteWithChildren
  '/whatsapp': typeof AppWhatsappRoute
  '/notifications/$id': typeof AppNotificationsIdRoute
  '/notifications/new': typeof AppNotificationsNewRoute
  '/wellness-programs/$id': typeof AppWellnessProgramsIdRoute
  '/wellness-programs/new': typeof AppWellnessProgramsNewRoute
  '/notifications/': typeof AppNotificationsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/devices': typeof AppDevicesRoute
  '/employees': typeof AppEmployeesRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/templates': typeof AppTemplatesRoute
  '/wellness-programs': typeof AppWellnessProgramsRouteWithChildren
  '/whatsapp': typeof AppWhatsappRoute
  '/': typeof AppIndexRoute
  '/notifications/$id': typeof AppNotificationsIdRoute
  '/notifications/new': typeof AppNotificationsNewRoute
  '/wellness-programs/$id': typeof AppWellnessProgramsIdRoute
  '/wellness-programs/new': typeof AppWellnessProgramsNewRoute
  '/notifications': typeof AppNotificationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/audit-logs': typeof AppAuditLogsRoute
  '/_app/devices': typeof AppDevicesRoute
  '/_app/employees': typeof AppEmployeesRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/templates': typeof AppTemplatesRoute
  '/_app/wellness-programs': typeof AppWellnessProgramsRouteWithChildren
  '/_app/whatsapp': typeof AppWhatsappRoute
  '/_app/': typeof AppIndexRoute
  '/_app/notifications/$id': typeof AppNotificationsIdRoute
  '/_app/notifications/new': typeof AppNotificationsNewRoute
  '/_app/wellness-programs/$id': typeof AppWellnessProgramsIdRoute
  '/_app/wellness-programs/new': typeof AppWellnessProgramsNewRoute
  '/_app/notifications/': typeof AppNotificationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/audit-logs'
    | '/devices'
    | '/employees'
    | '/reports'
    | '/settings'
    | '/templates'
    | '/wellness-programs'
    | '/whatsapp'
    | '/notifications/$id'
    | '/notifications/new'
    | '/wellness-programs/$id'
    | '/wellness-programs/new'
    | '/notifications/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/audit-logs'
    | '/devices'
    | '/employees'
    | '/reports'
    | '/settings'
    | '/templates'
    | '/wellness-programs'
    | '/whatsapp'
    | '/'
    | '/notifications/$id'
    | '/notifications/new'
    | '/wellness-programs/$id'
    | '/wellness-programs/new'
    | '/notifications'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/audit-logs'
    | '/_app/devices'
    | '/_app/employees'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/templates'
    | '/_app/wellness-programs'
    | '/_app/whatsapp'
    | '/_app/'
    | '/_app/notifications/$id'
    | '/_app/notifications/new'
    | '/_app/wellness-programs/$id'
    | '/_app/wellness-programs/new'
    | '/_app/notifications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/whatsapp': {
      id: '/_app/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AppWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wellness-programs': {
      id: '/_app/wellness-programs'
      path: '/wellness-programs'
      fullPath: '/wellness-programs'
      preLoaderRoute: typeof AppWellnessProgramsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees': {
      id: '/_app/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/devices': {
      id: '/_app/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AppDevicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit-logs': {
      id: '/_app/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AppAuditLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications/': {
      id: '/_app/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AppNotificationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wellness-programs/new': {
      id: '/_app/wellness-programs/new'
      path: '/new'
      fullPath: '/wellness-programs/new'
      preLoaderRoute: typeof AppWellnessProgramsNewRouteImport
      parentRoute: typeof AppWellnessProgramsRoute
    }
    '/_app/wellness-programs/$id': {
      id: '/_app/wellness-programs/$id'
      path: '/$id'
      fullPath: '/wellness-programs/$id'
      preLoaderRoute: typeof AppWellnessProgramsIdRouteImport
      parentRoute: typeof AppWellnessProgramsRoute
    }
    '/_app/notifications/new': {
      id: '/_app/notifications/new'
      path: '/notifications/new'
      fullPath: '/notifications/new'
      preLoaderRoute: typeof AppNotificationsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications/$id': {
      id: '/_app/notifications/$id'
      path: '/notifications/$id'
      fullPath: '/notifications/$id'
      preLoaderRoute: typeof AppNotificationsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppWellnessProgramsRouteChildren {
  AppWellnessProgramsIdRoute: typeof AppWellnessProgramsIdRoute
  AppWellnessProgramsNewRoute: typeof AppWellnessProgramsNewRoute
}

const AppWellnessProgramsRouteChildren: AppWellnessProgramsRouteChildren = {
  AppWellnessProgramsIdRoute: AppWellnessProgramsIdRoute,
  AppWellnessProgramsNewRoute: AppWellnessProgramsNewRoute,
}

const AppWellnessProgramsRouteWithChildren =
  AppWellnessProgramsRoute._addFileChildren(AppWellnessProgramsRouteChildren)

interface AppRouteChildren {
  AppAuditLogsRoute: typeof AppAuditLogsRoute
  AppDevicesRoute: typeof AppDevicesRoute
  AppEmployeesRoute: typeof AppEmployeesRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppWellnessProgramsRoute: typeof AppWellnessProgramsRouteWithChildren
  AppWhatsappRoute: typeof AppWhatsappRoute
  AppIndexRoute: typeof AppIndexRoute
  AppNotificationsIdRoute: typeof AppNotificationsIdRoute
  AppNotificationsNewRoute: typeof AppNotificationsNewRoute
  AppNotificationsIndexRoute: typeof AppNotificationsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditLogsRoute: AppAuditLogsRoute,
  AppDevicesRoute: AppDevicesRoute,
  AppEmployeesRoute: AppEmployeesRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppWellnessProgramsRoute: AppWellnessProgramsRouteWithChildren,
  AppWhatsappRoute: AppWhatsappRoute,
  AppIndexRoute: AppIndexRoute,
  AppNotificationsIdRoute: AppNotificationsIdRoute,
  AppNotificationsNewRoute: AppNotificationsNewRoute,
  AppNotificationsIndexRoute: AppNotificationsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
